/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Mcpgrid API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiException,
  CreateWaitlistRequest,
  CreateWaitlistResponse
} from '../api.schemas';

import { customInstance } from '../../utils/orval/orval.utils';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const createWaitlist = (
    createWaitlistRequest: CreateWaitlistRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateWaitlistResponse>(
      {url: `/api/waitlists`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWaitlistRequest, signal
    },
      options);
    }
  


export const getCreateWaitlistMutationOptions = <TError = ApiException,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWaitlist>>, TError,{data: CreateWaitlistRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createWaitlist>>, TError,{data: CreateWaitlistRequest}, TContext> => {

const mutationKey = ['createWaitlist'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWaitlist>>, {data: CreateWaitlistRequest}> = (props) => {
          const {data} = props ?? {};

          return  createWaitlist(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWaitlistMutationResult = NonNullable<Awaited<ReturnType<typeof createWaitlist>>>
    export type CreateWaitlistMutationBody = CreateWaitlistRequest
    export type CreateWaitlistMutationError = ApiException

    export const useCreateWaitlist = <TError = ApiException,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWaitlist>>, TError,{data: CreateWaitlistRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWaitlist>>,
        TError,
        {data: CreateWaitlistRequest},
        TContext
      > => {

      const mutationOptions = getCreateWaitlistMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    