/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Mcpbox API
 * OpenAPI spec version: 1.0.0
 */
export interface ServerItem {
  id: string;
  slug: string;
  title: string;
  owner: string;
  description: string;
  /** @nullable */
  icon: string | null;
  isOfficial: boolean;
  /** @nullable */
  logo: string | null;
}

export interface GetServersResponse {
  total: number;
  data: ServerItem[];
}

export type GetServersParams = {
take?: number;
skip?: number;
q?: string;
category?: string;
};

