import {
  BiBuildings,
  BiCalendarAlt,
  BiCodeAlt,
  BiCog,
  BiFile,
  BiGlobe,
  BiHome,
  BiInfoCircle,
  BiKey,
  BiLink,
  BiLogoGithub,
  BiPaperPlane,
  BiRocket,
  BiSolidBadgeCheck,
  BiUser,
  BiHash,
  BiLogoGoogle,
  BiSolidQuoteAltLeft,
  BiChevronDown,
  BiSolidUser,
  BiServer,
} from 'react-icons/bi';
import { MdBalance } from 'react-icons/md';

export const ICON_BX = {
  'calendar-alt': BiCalendarAlt,
  'chevron-down': BiChevronDown,
  'code-alt': BiCodeAlt,
  'info-circle': BiInfoCircle,
  'logo-git-hub': BiLogoGithub,
  'logo-google': BiLogoGoogle,
  'paper-plane': BiPaperPlane,
  'solid-badge-check': BiSolidBadgeCheck,
  'solid-quote-alt-left': BiSolidQuoteAltLeft,
  balance: MdBalance,
  buildings: BiBuildings,
  cog: BiCog,
  file: BiFile,
  globe: BiGlobe,
  hash: BiHash,
  home: BiHome,
  key: BiKey,
  link: BiLink,
  rocket: BiRocket,
  user: BiUser,
  server: BiServer,
  'solid-user': BiSolidUser,
};
