import {
  BiBuildings,
  BiCalendarAlt,
  BiCodeAlt,
  BiCog,
  BiFile,
  BiGlobe,
  BiHome,
  BiInfoCircle,
  BiKey,
  BiLink,
  BiLogoGithub,
  BiPaperPlane,
  BiRocket,
  BiSolidBadgeCheck,
  BiUser,
  BiHash,
  BiLogoGoogle,
} from 'react-icons/bi';
import { MdBalance } from 'react-icons/md';

export const ICON_BX = {
  'logo-google': BiLogoGoogle,
  'calendar-alt': BiCalendarAlt,
  'code-alt': BiCodeAlt,
  'info-circle': BiInfoCircle,
  'logo-git-hub': BiLogoGithub,
  'paper-plane': BiPaperPlane,
  'solid-badge-check': BiSolidBadgeCheck,
  balance: MdBalance,
  buildings: BiBuildings,
  cog: BiCog,
  file: BiFile,
  globe: BiGlobe,
  hash: BiHash,
  home: BiHome,
  key: BiKey,
  link: BiLink,
  rocket: BiRocket,
  user: BiUser,
};
