export * from './getAuth.page';
export * from './getDashboard.page';
export * from './getFaqs.page';
export * from './getHome.page';
export * from './getServer.page';
export * from './getServerOverview.page';
export * from './getServers.page';
export * from './getServerTools.page';
export * from './getSignIn.page';
