export enum RoutePath {
  Blog = '/blog',
  BlogPost = '/blog/:slug',
  ContactUs = '/contact-us',
  Faqs = '/faqs',
  Index = '/',
  SignIn = '/signin',
  SignUp = '/signup',
  Dashboard = '/dashboard',
  Servers = '/servers',
  ServerDetails = '/servers/:slug',
  ServerDetailsTools = '/servers/:slug/tools',
  ServerDetailsReadme = '/servers/:slug/readme',
  Admin = '/admin',
  AdminServers = '/admin/servers',
  Profile = '/profile',
}
