name: Deploy

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Deploy to Google Cloud App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: |-
            PRODUCT_NAME=${{ vars.PRODUCT_NAME }}
            STRAPI_HOST=${{ secrets.STRAPI_HOST }}
            STRAPI_API_TOKEN=${{ secrets.STRAPI_API_TOKEN }}

      - name: Remove Cloud App Engine versions
        uses: Reviewable/appengine-remove-action@v2.1.2
        with:
          limit: 1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS_JSON }}
