name: Deploy

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      environment:
        type: environment

env:
  GOOGLE_ANALYTICS_ID: G-BSC823LMT3
  PRODUCT_NAME: Mcpgrid

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Google Cloud App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: |-
            PRODUCT_NAME=${{ env.PRODUCT_NAME }}
            API_HOST=${{ vars.API_HOST }}
            KEYSTONE_SCHEMA_URL=${{ secrets.KEYSTONE_GRAPHQL_SCHEMA_URL }}
            GOOGLE_ANALYTICS_ID=${{ env.GOOGLE_ANALYTICS_ID }}
            NEXTAUTH_URL=http://mcpgrid.ai
            NEXTAUTH_SECRET=${{ secrets.SESSION_SECRET }}
            GCP_FIREBASE_ACCOUNT_KEY=${{ secrets.GCP_FIREBASE_ACCOUNT_KEY }}

      - name: Remove Cloud App Engine versions
        uses: Reviewable/appengine-remove-action@v2.1.2
        with:
          limit: 1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Warm up service
        run: |
          for i in {1..5}; do
            curl -fsS "${{ steps.deploy.outputs.url }}" && exit 0
            echo "Retrying in 3s..."
            sleep 3
          done
          echo "Service did not respond successfully" && exit 1
